spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fm
    username: fm
    password: fm
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    baseline-on-migrate: true

server:
  port: 8080

s3:
  bucket: ********
  access-key: ********
  secret-key: *******************
  service-endpoint: sfo2.digitaloceanspaces.com
  signing-region: sfo2
